[build]
  publish = "dist"
  functions = "functions"

[build.environment]
  NODE_VERSION = "20.18.0"
  NPM_VERSION = "10.8.2"

[context.production]
  command = "bun run build"

[context.deploy-preview]
  command = "bun run build"

[context.branch-deploy]
  command = "bun run build"

[context.next]
  command = "bun run build"

# Redirects and rewrites — https://docs.netlify.com/routing/redirects/#syntax-for-the-netlify-configuration-file
[[redirects]]
  from = "/"
  to = "/getting-started/"
  status = 301
  force = true

[[redirects]]
  from = "/install/"
  to = "/install/auto/"
  status = 301
  force = true

[[redirects]]
  from = "https://docs.gethyas.com/*"
  to = "https://docs.thulite.io/:splat"
  status = 301
  force = true

# Custom headers — https://docs.netlify.com/routing/headers/#syntax-for-the-netlify-configuration-file
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    # Content-Security-Policy = "default-src 'self'; manifest-src 'self'; connect-src 'self'; font-src 'self'; img-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'"
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "strict-origin"
    Permissions-Policy = "geolocation=(self), microphone=(), camera=()"
    Cache-Control= '''
    public,
    max-age=604800,
    immutable'''
    Access-Control-Allow-Origin = "*"
